location /artifacts/ {
    auth_request /auth/artifact;
    alias /srv/conos/status/artifacts/;
}

location = /auth/artifact {
    internal;
    proxy_pass http://unix:/run/conos/artifact-auth.sock;
    proxy_pass_request_body off;
    proxy_set_header Content-Length "";
    proxy_set_header X-Original-URI $request_uri;
}
